### ISSUE TITLE
Lynx-Support könnte besser sein

### ISSUE THREAD

**Issue by spilot** [AStA-TU-Darmstadt/eleFant#3]
Das Antragsformular ist in Lynx recht gut zu benutzen. Die Startseite hat aber noch Verbesserungspotential. Hier ein Screenshot:

![bildschirmfoto vom 2017-04-26 11-14-50](https://cloud.githubusercontent.com/assets/12112224/25427114/d6a702fa-2a71-11e7-9646-61201439dd9a.png)

**Comment by haaase** [comment]
Sorry, aber Lynx ist nun wirklich nicht der reference Browser. Vielleicht gibt es irgendwann ein REST Interface und dann können wir gerne einen Command-Line Client schreiben.
